WRAPPER =   '[WRAPPER] '
DEBUG =     '[DEBUG  ] '
ERROR =     '[ERROR  ] '
WARNING =   '[WARNING] '
SUCCESS =   '[SUCCESS] '
FAILURE =   '[FAILURE] '
SETTING =   '[SETTING] '

NEW_LINE = '''\n'''
BAR_N = '''\\n'''
SPACE = ''' '''
NOTHING = ''''''
TRIPLE_SINGLE_QUOTE = """'''"""
TRIPLE_DOUBLE_QUOTE = '''"""'''
SINGLE_QUOTE = """'"""
DOUBLE_QUOTE = '''"'''
COMA = ''','''
COLON = ''':'''
BACK_SLASH = '''\\'''
SLASH = '''/'''
HASH_TAG = '''#'''
SPACE = ''' '''
DOT = '''.'''
DASH = '''-'''
SPACE_DASH_SPACE = ''' - '''
UNDERSCORE = '''_'''
DOT_SPACE = '''. '''
COLON_SPACE = ''': '''
SPACE_COLON_SPACE = ''' : '''
LOG_CAUSE = '''Cause'''

TAB_UNITS = 4
TAB = TAB_UNITS * SPACE

TRUE = 'True'
FALSE = 'False'

BOOLEAN = 'bool'
STRING = 'str'
INTEGER = 'int'
TUPLE = 'tuple'
LIST = 'list'
DICT = 'dict'

OPEN_TUPLE = '('
CLOSE_TUPLE = ')'
OPEN_LIST = '['
CLOSE_LIST = ']'
OPEN_DICTIONARY = '{'
CLOSE_DICTIONARY = '}'
